spring:
  application:
    name: springStudy

  datasource:
    url: ${STUDY_DB}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

server:
  port: 8080

#Token
JWT:
  SECRET_KEY: ${SECRECT}